spring:
  jpa:
    database-platform : org.hibernate.dialect.MySQLDialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bookstore?serverTimezone=UTC&characterEncoding=UTF-8
    username : root
    password :
  batch:
    job:
      enabled: false
  main:
    allow-bean-definition-overriding: true

server:
  port: 8084

yalooStore:
  front: http://localhost:8082
  shop : http://localhost:8081
  gateway: http://localhost:7080
  auth: http://localhost:8083



