
spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bookstore?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password:

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

  main:
    allow-bean-definition-overriding: true
