spring:
  profiles:
    include: prod

server:
  port: 8084

yalooStore:
  front: http://localhost:8082
  shop : http://localhost:8081
  gateway: http://localhost:7080
  auth: http://localhost:8083



