spring:
  jpa:
    database-platform : org.hibernate.dialect.MySQLDialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bookstore?serverTimezone=UTC&characterEncoding=UTF-8
    username : root
    password :
  batch:
    job:
      enabled: false

server:
  port: 8084

yalooStore:
  front: localhost:8082
  shop : localhost:8081
  gateway: localhost:7080
  auth: localhost:8083

